<?php


namespace app\admin\controller;



use think\Controller;

class Shuju extends Controller
{public function  _initialize()
{
	parent::_initialize(); // TODO: Change the autogenerated stub
}
   public function shuju(){
	   return view('index');
}
}