<?php


namespace app\admin\controller;


use think\Collection;
use think\Controller;
use think\Db;

class Nav extends Bace
{
	public function  _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
	}

	public function index(){
	//查看页面
	return view('index');
    }
    public function openinsert(){
	//展示插入页面
    return view('openinsert');
    }

//插入逻辑
    public function insert(){
    //权限   请求方式  参数
	$method = $this->request->method();
	if ($method !='POST'){
		return json(['code'=>404,'msg'=>"请求方式错误"]);
	}
	//验证规则
	$data=input('post.');
	$validate=validate('Nav');
	if (!$validate->scene('insert')->check($data)){
		return json(['code'=>404,'msg'=>$validate->getError()]);
	}
	//插入数据
	$result=Db::table('nav')->insert($data);
	if ($result>0){
		return json(['code'=>200,'msg'=>"导航插入成功"]);
	} else {
		return json(['code'=>404,'msg'=>"导航插入失败"]);
	}
}

    public function query(){
    $data=Db::table('nav')->select();
	    $count=Db::table('nav')->count();
     return json([
	     'code'=>0,
	     'msg'=>'成功',
	     'count'=>$count,
	     'data'=>$data
     ]);
   }
	public function delete(){
//		$data=input('post.');
		if (!$this->request->isPost()){
			return json(['code'=>404,'msg'=>"请求方式错误"]);
		}
		//验证规则
		$data=input('post.');
		$validate=validate('Nav');
		if (!$validate->scene('delete')->check($data)){
			return json(['code'=>404,'msg'=>$validate->getError()]);
		}
		$result=Db::table('nav')->where('id',$data['id'])->delete();
		if ($result>0){
			return json(['code'=>200,'msg'=>"删除成功"]);
		} else {
			return json(['code'=>404,'msg'=>"删除失败"]);
		}
	}

	public function update(){
		if (!$this->request->isPost()){
			return json(['code'=>404,'msg'=>"请求方式错误"]);
		}
		//验证规则
		$data=input('post.');
		var_dump($data);
		$validate=validate('Nav');
		if (!$validate->scene('update')->check($data)){
			return json(['code'=>404,'msg'=>$validate->getError()]);
		}
		$result=Db::table('nav')->where('id',$data['id'])
			->update([$data['field']=>$data['value']]);
		if ($result>0){
			return json(['code'=>200,'msg'=>"更新成功"]);
		} else {
			return json(['code'=>404,'msg'=>"更新失败"]);
		}
	}
}