<?php


namespace app\admin\controller;


use think\Controller;

class News extends Bace
{
	public function  _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
	}
	function index(){
		return "fdds ";
	}
	function insert(){

	}
	function updata(){

	}

}